# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Recall These Thoughts
email: info@scottlougheed.com
description: Inanity from Scott Lougheed, PhD
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://scottlougheed.com" # the base hostname & protocol for your site
twitter_username: scottisloud
github_username:  scottisloud
pagination:
 enabled: true
 per_page: 10
 sort_reverse: true
 permalink: '/page:num/'
defaults:
  -
    scope:
      path: 'dnd/_posts'
    values:
      hidden: 'true'
      layout: 'dnd_post'
      permalink: '/:categories/:title.html'
# Build settings
markdown: kramdown
kramdown:
  parse_block_html: false
  syntax_highlighter: rouge
# destination: scottlougheed.com
plugins: [jekyll-paginate-v2, jekyll-twitter-plugin]
