# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Recall These Thoughts
email: info@scottlougheed.com
description: Inanity from Scott Lougheed, PhD
baseurl: # the subpath of your site, e.g. /blog
url: "https://scottlougheed.com" # the base hostname & protocol for your site
twitter_username: scottisloud
github_username:  scottisloud
pagination:
 enabled: true
 per_page: 15
 sort_reverse: true
 permalink: '/page:num/'
# Build settings
markdown: kramdown
kramdown:
  parse_block_html: false
  #html_to_native: true
plugins: [jekyll-paginate-v2, jekyll-twitter-plugin]
